### PR TITLE
Feature/284 reuse settings plus bugfixes

### LINKED ISSUE #279: Export to Zip issue
## Issue Description
The `Export to Zip` button seems to fail when multiple files have been selected. 
Screenshot from 2022-03-16 11-29-34

## Version / Environment information
UI: `1.11.3`
Oasis: `1.24.0`

## Example data / logs
Error warnings from UI application

```
Warning: Error in fwrite: Column 4's length (0) is not the same as column 1's length (1)
  [No stack trace available]
Read 64 items
```

```
Warning: Error in fwrite: Row 1 of list column is type 'list' - not yet implemented. fwrite() can write list columns containing items which are atomic vectors of type logical, integer, integer64, double, complex and character.
  [No stack trace available]
```

### LINKED ISSUE #281: Error when trying to view IG Logs
## Issue Description
Nothing happens when I click "View IG Logs" after input generation.

## Steps to Reproduce (Bugs only)
1. Create an analysis and run input generation
2. Click "Show IG Log"

## Version / Environment information
UI Version 1.1.3
coreoasis/api_server:1.23.8 

## Example data / logs
```
oasis-ui_1        | No encoding supplied: defaulting to UTF-8.
oasis-ui_1        | Warning: Error in FUN: argument is not a character vector
oasis-ui_1        |   2: runApp
oasis-ui_1        |   1: oasisui::runOasisui
```

### LINKED ISSUE #284: Save/Recover Analysis Settings
## Issue Description
Add functionality to the UI to allow analysis settings to be saved and retrieved using the setting_template endpoints

https://github.com/OasisLMF/OasisPlatform/pull/621

Users should be able to 

- click a "Save Settings" button after they have entered all of their run time options
- retrieve a list of previously saved settings files as a drop down and apply to the run

### PR DESCRIPTION
**Pull request by RolandASc**
closes #284 
fixes #279 
fixes #281 
partially addresses #266 

### Analysis settings templates functionality
* Allows to select a previously saved analysis settings template (attached to the same model) in the output configuration step.
 When the analysis is ready to execute, the settings can also be saved as a new settings template.
  In addition, setting templates can be managed by deleting obsolete ones.

* Fixes a bug downloading files of certain formats.

### CODE REVIEW

**Review by sambles — CHANGES_REQUESTED** [review]
Issues https://github.com/OasisLMF/OasisUI/issues/284 and https://github.com/OasisLMF/OasisUI/issues/279 look good 

I'm hitting problems with displaying both the input generation and loss generation logs: 
1. clicking ''Show IG Log" crashes the application
```
.reloadSummary_total called
updating result$anaID because submodulesList$step2_chooseAnalysis$analysisID() changed to: 1
changing result$counter because counter() changed to 20
showing panelAnalysisLog
.reloadAnaLog called
No encoding supplied: defaulting to UTF-8.
Warning: Error in FUN: argument is not a character vector
  2: runApp
  1: oasisui::runOasisui
re-rendering analysis log table
```
2. The download button under "Show Run Log" seems to fail 
Screenshot from 2022-07-27 11-46-41

```
showing analysis run log table
.reloadAnaRunLog called
Warning in value[[3L]](cond) : Not Found (HTTP 404).
Warning in self$api_handle_response(response) :
  Client error in api_handle_response, valid query but API did not find / return the requested resource.
re-rendering analysis log table
.clearOutputOptions called
replacing icons
updating output parameters for Summary configuration and cleaning up UI
input$dt_analyses_rows_selected is changed to: 2
analysisId changed to 1
re-rendering analysis log table
showing analysis run log table
.reloadAnaRunLog called
No encoding supplied: defaulting to UTF-8.
re-rendering analysis log table
Warning: Error in fwrite: Column 2's length (0) is not the same as column 1's length (1)
  [No stack trace available]
```

**Comment by RolandASc** [comment]
thanks for the testing and feedback @sambles.

it looks like with the first point you have actually ran into #281 , so I'll check that and hopefully we can close that issue together with this PR :+1:

**Comment by sambles** [comment]
I also noticed the loss output log file generated by the worker `1.26.0` was quite large for a text file (its a Platform issue and not really UI related)

But that seemed to cause the UI slow downs when displaying the logs. Not really unexpected, but something to watch out for. 


The file was around 44Mb~  (350k lines, mostly of numba debug logs)

**Comment by RolandASc** [comment]
yes, indeed, I have observed that as well, rendering such large log files slows the UI down a lot, which the user may interpret as the UI freezing

would have to check if we could do something like a line-count first to address this (possibly separate issue)

**Comment by RolandASc** [comment]
@sambles 
I fixed the additional issues with log files spotted during testing in [f845d85](https://github.com/OasisLMF/OasisUI/pull/289/commits/f845d85f1ba503d4eb3970b5914d8238aefea408)

**Review by sambles — APPROVED** [review]
Looks good

**Pull request merged**
